name: zego_zimkit
description: A low-code plugin that provides a wrapper for IM widgets. Aims to simplify the development process by offering a user-friendly solution into applications.
version: 1.19.4
homepage: https://www.zegocloud.com/

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_plugin_adapter: ^2.13.11
  zego_uikit_signaling_plugin: ^2.8.17
  zego_zim: ^2.21.1+2
  zego_zim_audio: ^1.0.0+7
  zego_callkit: ^1.0.0+5

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  encrypt: ^5.0.3
  flutter_logs_yoer: ^2.2.1
  async: ^2.0.0
  video_player: ^2.10.0
  file_picker: ^10.1.2
  chewie: ^1.10.0
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.1.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0 # run 'flutter pub run import_sorter:main'
  lints: ^3.0.0

import_sorter:
  comments: false

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.zegocloud.uikit.zimkit_plugin
        pluginClass: ZegoUIKitZIMKitPlugin
      ios:
        pluginClass: ZegoUIKitZIMKitPlugin

screenshots:
  - description: "A full-featured chat kit that enables you to easily build one-on-one or group chat into your app in minutes."
    path: images/img_chat.png
